branches:
  only:
  - master

language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10
      install:
        - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-macosx.tar.gz -O premake.tar.gz
        - tar -xzf premake.tar.gz
      script:
        - ./premake5 gmake2 --skip_shader_validation
        - cd build/
        - make ALL
        - cd ..
    - os: linux
      dist: bionic
      compiler: gcc
      before_install:
        - sudo apt-get install -y libgtk-3-dev
      install:
        - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz -O premake.tar.gz
        - tar -xzf premake.tar.gz
      script:
        - ./premake5 gmake2 --skip_shader_validation
        - cd build/
        - make ALL
        - cd ..
    - os: linux
      dist: bionic
      compiler: clang
      before_install:
        - sudo apt-get install -y libgtk-3-dev
      install:
        - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz -O premake.tar.gz
        - tar -xzf premake.tar.gz
      script:
        - ./premake5 gmake2 --skip_shader_validation
        - cd build/
        - make ALL
        - cd ..
    - os: windows
      install:
        - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-windows.zip -O premake.zip
        - 7z e premake.zip
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - ./premake5 vs2017 --skip_shader_validation
        - cd build
        - MSBuild.exe Rendu.sln //t:Meta\\ALL //m:2 //nologo //verbosity:minimal //p:Configuration=Release //p:Platform=x64
        - cd ..

