# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  
  document:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          path: rendu
      - name: Build doc
        working-directory: ${{github.workspace}}/rendu
        run: |
          ls -l -a
          sudo apt-get update -y && sudo apt-get install -yq doxygen
          doxygen docs/Doxyfile
          
      - uses: actions/checkout@v2
        with:
          repository: kosua20/Rendu-documentation
          path: doc
      
      - name: Upload doc
        working-directory: ${{github.workspace}}/doc
        run: |
          ls -l -a
          cp -r ${{github.workspace}}/rendu/docs/html/ ./
          git config user.name "Simon Rodriguez"
          git config user.email kosua20@gmail.com
          git add .
          git commit -m "Documentation: update (via CI)."
          git push
      
    
  
