

name: Documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  
  document:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone code repository
        uses: actions/checkout@v2
        with:
          path: rendu
          persist-credentials: false
     
      - name: Build documentation
        working-directory: ${{github.workspace}}/rendu
        run: |
          sudo apt-get update -y && sudo apt-get install -yq doxygen
          doxygen docs/Doxyfile
          
      - name: Clone documentation repository
        uses: actions/checkout@v2
        with:
          repository: kosua20/Rendu-documentation
          path: doc
          persist-credentials: true
          token: ${{ secrets.DOC_TOKEN }}
      
      - name: Upload documentation
        working-directory: ${{github.workspace}}/doc
        run: |
          git config user.name "Simon Rodriguez"
          git config user.email kosua20@gmail.com
          git rm -rf .
          cp -r ../rendu/docs/html/* ./
          git add .
          git diff-index --quiet HEAD || git commit -a -m "Documentation: update (via CI)."
          git push
